version: '3.8'

services:
  db:
    image: postgres:15
    container_name: walletwatch-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:?DB_USER is required}
      POSTGRES_PASSWORD: ${DB_PASS:?DB_PASS is required}
      POSTGRES_DB: ${DB_NAME:?DB_NAME is required}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/init_data/create.sql:/docker-entrypoint-initdb.d/00-create.sql
      - ./src/init_data/insert.sql:/docker-entrypoint-initdb.d/01-insert.sql

  app:
    image: node:18
    container_name: walletwatch-app
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm run testandrun"
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
